### PR TITLE
nuttx: esp32s3: fix compilation when enable mbedTLS in apps

### PR DESCRIPTION
**Pull request by pkarashchenko**

### CODE REVIEW

**Comment by tmedicci** [comment]
Hi @pkarashchenko ! Thanks for submitting it. Could you please provide a background (about what is failing on NuttX) and how to reproduce the issue?

**Comment by pkarashchenko** [comment]
I'm trying to enable mbedTLS in NuttX app and build MQTT-C mbedTLS example.

**Comment by tmedicci** [comment]
> I'm trying to enable mbedTLS in NuttX app and build MQTT-C mbedTLS example.

Thanks. I'll check...

Note that, for now, you can override the HAL with your own without changing any source code on NuttX. Just set env `ESP_HAL_3RDPARTY_URL` and `ESP_HAL_3RDPARTY_VERSION` before building. For instance:

```
ESP_HAL_3RDPARTY_URL="git@github.com:tmedicci/esp-hal-3rdparty.git" ESP_HAL_3RDPARTY_VERSION="improvement/rmt_driver" make
```

**Comment by pkarashchenko** [comment]
Yes. I know. Initially I passed the build with only patching a header file, but later naming conflict happened when I enabled mbedTLS for MQTT

**Comment by pkarashchenko** [comment]
Do you have results from internal CI?

**Comment by tmedicci** [comment]
> Do you have results from internal CI?

I'm testing it right now. Yesterday afternoon I had another professional commitment.

We have an almost automated way of setting the prefixes (I'll make it public). There are other cases for inline functions that need to be set too. I'll let you know asap...

**Comment by tmedicci** [comment]
@pkarashchenko , can you please double-check https://github.com/tmedicci/esp-hal-3rdparty/tree/bugfix/nuttx_mbedtls?

**Comment by tmedicci** [comment]
> @pkarashchenko , can you please double-check https://github.com/tmedicci/esp-hal-3rdparty/tree/bugfix/nuttx_mbedtls?

Any updates about it @pkarashchenko ?

**Comment by pkarashchenko** [comment]
Will try out till Friday. Sorry, I'm having a busy week

**Comment by pkarashchenko** [comment]
@tmedicci hi. Change works for me, but I posted one comment https://github.com/tmedicci/esp-hal-3rdparty/commit/6fc8272dabb81239ba42e2107a20c4be1a0a897e#r139129194

**Comment by tmedicci** [comment]
> @tmedicci hi. Change works for me, but I posted one comment [tmedicci@6fc8272#r139129194](https://github.com/tmedicci/esp-hal-3rdparty/commit/6fc8272dabb81239ba42e2107a20c4be1a0a897e#r139129194)

Could you please double-check same branch?

**Comment by pkarashchenko** [comment]
Works well for me!

**Comment by tmedicci** [comment]
Solved with https://github.com/espressif/esp-hal-3rdparty/commit/55b60d9ed1930f7a284fe0555a17db441cee9ab4. Thanks @pkarashchenko !

**Pull request closed without merging**
